#!/usr/bin/env bash

_date="date"

ts=$($_date --date="$($_date --date='next month' +'%Y-%m')-01 -1 day" +'%s')
day=$($_date --date="@$ts" +'%d')
date=$($_date --date="@$ts" +"%Y-%b-%d")
year=$($_date --date="@$ts" +"%Y")
month=$($_date --date="@$ts" +"%b-$day")
title="Monthly Update: $($_date --date="@$ts" +'%B %Y')"

prev=$($_date --date="$($_date +'%Y-%m')-01 -1 day" +'%Y-%b-%d')

date=${date,,} # lowercase
month=${month,,} # lowercase
prev=${prev,,} # lowercase
slug="monthly-update"

cd "$(dirname "${BASH_SOURCE[0]}")"
cd ..

fdir="${slug}/${year}"
file="${fdir}/${month}.md"

if [ ! -f "$file" ]; then
mkdir -p "${fdir}"
cat <<FILE > "$file"
---
# vim: tw=80
title: "${title}"
date: $(date --date="@$ts" +"%Y-%m-%dT20:00:00%:z")
tags:
  - ${slug}
parents:
  - "${prev}/${slug}"
---

## Fiction

FILE
fi

echo "$file"
nvim +12 "$file"
git add "$file"
