#!/usr/bin/env bash

if which gdate 2>/dev/null; then
  _date="gdate"
else
  _date="date"
fi

if [ "$(date +%d)" -lt 10 ]; then
  date=$($_date +"%Y-%b-10")
  year=$($_date +"%Y")
  month=$($_date +"%b-10")
  title="Monthly Update: $($_date +'%B %Y')"
  prev=$($_date --date='last month' +"%Y/%b/10")
else
  date=$($_date --date='next month' +"%Y-%b-10")
  year=$($_date --date='next month' +"%Y")
  month=$($_date --date='next month' +"%b-10")
  title="Monthly Update: $($_date --date='next month' +'%B %Y')"
  prev=$($_date +"%Y/%b/10")
fi

date=${date,,} # lowercase
month=${month,,} # lowercase
prev=${prev,,} # lowercase
slug="monthly-update"

cd "$(dirname "${BASH_SOURCE[0]}")"
cd ..

fdir="${slug}/${year}"
file="${fdir}/${month}.md"

if [ ! -f "$file" ]; then
mkdir -p "${fdir}"
cat <<FILE > "$file"
---
# vim: tw=80
title: "${title}"
tags:
  - ${slug}
parents:
  - "${prev}/${slug}"
---

## Heading
FILE
fi

echo "$file"
nvim +10 "$file"
git add "$file"
