#!/usr/bin/bash

datetime=$(date --iso-8601=seconds)
date=$(date +"%Y-%b-%d")
date=${date,,}
title="$@"
slug=${title// /-}

dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
file="${dir}/../${date}-${slug,,}.md"

cp "$dir/template.md" "$file"
sed -i "s/%DATE%/${datetime}/" "$file"
git add "$file"
e "$file"
