#!/usr/bin/bash

date=$(date +"%Y-%b-%d")
date=${date,,}
title="$@"
slug=${title// /-}

dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
file="${dir}/../${date}-${slug,,}.md"

cp "$dir/template.md" "$file"
git add "$file"
e "$file"
