#!/usr/bin/bash

datetime=$(date --iso-8601=seconds)
date=$(date +"%Y-%b-%d")
date=${date,,}
title="$@"
slug=${title// /-}

dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd .. && pwd)"
file="${date}-${slug,,}.md"
path="${dir}/${file}"

if [ ! -f "$path" ]; then
  cat <<TEMPLATE > "$path"
---
date: $datetime
title: $title
---

## Heading
TEMPLATE
  git add "$path"
else
  echo "File already exists" >&2
fi

echo "$file"
exec $EDITOR "$path"
