#!/usr/bin/bash

if [ "$(date +%d)" -lt 10 ]; then
  date=$(date +"%Y-%b-10")
  title="Monthly Update: $(date +'%B %Y')"
  prev=$(date --date='last month' +"%Y/%b/10/${slug}")
else
  date=$(date --date='next month' +"%Y-%b-10")
  title="Monthly Update: $(date --date='next month' +'%B %Y')"
  prev=$(date +"%Y/%b/10/${slug}")
fi

date=${date,,} # lowercase
prev=${prev,,} # lowercase
slug="monthly-update"

dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
file="${dir}/../${date}-${slug}.md"

if [ ! -f "$file" ]; then
cat <<FILE > "$file"
---
title: "${title}"
tags:
  - ${slug}
parents:
  - "${prev}/${slug}"
---

## Heading
FILE
fi

echo "${date}-${slug}.md"
nvim +10 "$file"
git add "$file"
