#!/usr/bin/bash

date=$(date --date='next month' +"%Y-%b-10")
date=${date,,} # lowercase

title="Monthly Update: $(date --date='next month' +'%B %Y')"
slug="monthly-update"

prev=$(date +"%Y/%b/10/${slug}")
prev=${date,,} # lowercase

dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
file="${dir}/../${date}-${slug}.md"

if [ ! -f ]; then
cat <<FILE > "$file"
---
title: "${title}"
tags:
  - ${slug}
parents:
  - "${prev}/${slug}"
---

## Fanfiction
FILE
fi

echo "${date}-${slug}.md"
nvim +10 "$file"
git add "$file"
